**660710717** **นางสาวนฤมล** **เวฬุวิริยกุล**

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

เป็นการ import library ของ python มาก่อน import **แค่ครั้งเดียวพอ**

In [5]:
from google.colab import files
uploaded = files.upload()

Saving student.csv to student.csv

อัปโหลดไฟล์ที่เซฟไว้ในเครื่องขึ้น colab

In [13]:
df_master = pd.read_csv('student.csv')

อ่านไฟล์ที่เราอัปขึ้นมา ตั้งชื่อไว้เพื่อใช้ต่อ

In [14]:
df_master.head()

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27

เช็ค head ของไฟล์นี้

In [15]:
base_date = datetime(2024, 1, 15)

datetime ในที่นี้คือการสร้างวันที่ datetime ทำได้อีกหลายแบบ คำนวนระยะเวลาได้ หรือ จะเป็น ดึงข้อมูลพวก วัน เดือน ปี จากวันเวลา

In [16]:
df_master['วันที่ลงทะเบียน'] = [base_date + timedelta(days=np.random.randint(-30, 30))
                                for _ in range(20)]

สุ่มสร้างวันที่ลงทะเบียนจำนวน 20 วัน

In [17]:
print("="*50)
print("🎯 ข้อมูลหลัก (Master Dataset) ที่จะใช้ตลอดบทเรียน")
print("="*50)
print(df_master)
print("\n📊 สรุปปัญหาที่พบในข้อมูล:")
print(f"- ค่าหายทั้งหมด: {df_master.isnull().sum().sum()} ค่า")
print(f"- อายุผิดปกติ: {df_master[df_master['อายุ'] > 100]['อายุ'].values if any(df_master['อายุ'] > 100) else 'ไม่มี'}")
print(f"- GPA ผิดปกติ: {df_master[(df_master['GPA'] < 0) | (df_master['GPA'] > 4)]['GPA'].values if any((df_master['GPA'] < 0) | (df_master['GPA'] > 4)) else 'ไม่มี'}")
print(f"- รูปแบบการเขียนคณะ: {df_master['คณะ'].nunique()} แบบ")
print(f"- รูปแบบการเขียนเพศ: {df_master['เพศ'].nunique()} แบบ")

==================================================
🎯 ข้อมูลหลัก (Master Dataset) ที่จะใช้ตลอดบทเรียน
==================================================
    รหัสนักศึกษา      ชื่อ   อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001     สมชาย   20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1          64002    สมหญิง   21.0    หญิง           วิทย์  3.45       165.0
2          64003       NaN    NaN    Male         Science  3.67       175.0
3          64004  สมศักดิ์   22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4          64005      สมใจ   19.0       ญ           วิศวะ  3.89       160.0
5          64006     กานต์  150.0     ชาย     Engineering  3.12       172.0
6          64007     กิตติ   21.0    หญิง        วิศวกรรม  4.50       158.0
7          64008      จิรา   20.0       F      ศิลปศาสตร์  2.98       180.0
8          64009    ชนาธิป   23.0       M            Arts  3.34       163.0
9          64010      ดารา   21.0    หญิง           ศิลป์  3.56       167.0
10         64011      ธีระ    NaN     NaN             NaN  3.78         NaN
11         64012       นภา   22.0     ชาย           วิทย์   NaN       171.0
12         64013     บุญมี   20.0    หญิง           วิศวฯ  3.23       169.0
13         64014     ปรีชา   21.0     ชาย    Liberal Arts  3.45       164.0
14         64015     พิมพ์   22.0  Female             Sci  3.67       162.0
15         64016      ภูมิ   19.0       ช     วิทยาศาสตร์  3.89       173.0
16         64017      มานี   20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0
17         64018      ยุพา   21.0    หญิง             NaN  3.23       161.0
18         64019     รัตนา    NaN     ชาย      ศิลปศาสตร์   NaN       174.0
19         64020     ลัดดา   22.0     NaN         Science  3.45       168.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-01-01
1         58.0                     20.0      2024-02-07
2          NaN                     25.0      2024-01-19
3         70.0                     10.0      2024-01-02
4         52.0                     30.0      2024-01-24
5         75.0                     12.0      2023-12-19
6         48.0                     35.0      2024-01-22
7         82.0                     18.0      2024-02-09
8         55.0                     22.0      2024-01-31
9         60.0                     28.0      2024-01-19
10        68.0                      NaN      2024-01-25
11         NaN                     16.0      2023-12-17
12        72.0                     24.0      2024-01-15
13        54.0                     19.0      2023-12-25
14        56.0                     26.0      2024-01-23
15        78.0                     14.0      2024-01-05
16        62.0                     21.0      2024-01-19
17        50.0                     27.0      2023-12-28
18        76.0                      NaN      2024-01-10
19        64.0                     23.0      2024-01-25

📊 สรุปปัญหาที่พบในข้อมูล:
- ค่าหายทั้งหมด: 15 ค่า
- อายุผิดปกติ: [150.]
- GPA ผิดปกติ: [-1.   4.5]
- รูปแบบการเขียนคณะ: 14 แบบ
- รูปแบบการเขียนเพศ: 8 แบบ

แสดงข้อมูลออกมา

In [18]:
df_original = df_master.copy()

เก็บสำเนาข้อมูลต้นฉบับ

In [19]:
df_master.isnull().sum().sum()

np.int64(15)

นับจำนวนค่าว่างทั้งหมดใน dataframe

In [20]:
df_master['คณะ'].nunique()

14

จำนวนที่ไม่ซ้ำกัน

In [25]:
df_master['คณะ'].unique()

array(['วิทยาศาสตร์', 'วิทย์', 'Science', 'คณะวิทยาศาสตร์', 'วิศวะ',
       'Engineering', 'วิศวกรรม', 'ศิลปศาสตร์', 'Arts', 'ศิลป์', nan,
       'วิศวฯ', 'Liberal Arts', 'Sci', 'วิศวกรรมศาสตร์'], dtype=object)

เรียกดูค่าที่ไม่ซ้ำกันทั้งหมดใน คอลัม คณะ

In [26]:
df_master

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-01
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-07
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-19
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-02
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-24
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-19
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-22
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-09
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-01-31
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-19
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-25
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-17
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2024-01-15
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2023-12-25
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-01-23
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-05
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-19
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2023-12-28
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-10
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-25

แสดงข้อมูลของชื่อที่เราใช้ออกมา แบบนี้ดูง่ายกว่าตอนแรก

In [27]:
df_master.shape

(20, 10)

ดูขนาดของ DataFrame df_master

In [23]:
print("="*50)
print("📋 ข้อมูลทั่วไปของ Dataset")
print("="*50)
df_master.info()

print("\n" + "="*50)
print("📊 สถิติเชิงพรรณนา")
print("="*50)
print(df_master.describe())

==================================================
📋 ข้อมูลทั่วไปของ Dataset
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   รหัสนักศึกษา             20 non-null     int64
 1   ชื่อ                     19 non-null     object
 2   อายุ                     17 non-null     float64
 3   เพศ                      18 non-null     object
 4   คณะ                      18 non-null     object
 5   GPA                      18 non-null     float64
 6   ส่วนสูง_cm               19 non-null     float64
 7   น้ำหนัก_kg               18 non-null     float64
 8   ชั่วโมงเรียน_ต่อสัปดาห์  18 non-null     float64
 9   วันที่ลงทะเบียน          20 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(5), int64(1), object(3)
memory usage: 1.7+ KB

==================================================
📊 สถิติเชิงพรรณนา
==================================================
       รหัสนักศึกษา        อายุ        GPA  ส่วนสูง_cm  น้ำหนัก_kg  \
count      20.00000   17.000000  18.000000   19.000000   18.000000
mean    64010.50000   28.470588   3.246111  167.684211   63.611111
min     64001.00000   19.000000  -1.000000  158.000000   48.000000
25%     64005.75000   20.000000   3.215000  163.500000   55.250000
50%     64010.50000   21.000000   3.450000  168.000000   63.000000
75%     64015.25000   22.000000   3.670000  171.500000   71.500000
max     64020.00000  150.000000   4.500000  180.000000   82.000000
std         5.91608   31.337114   1.123326    5.706260   10.279270

       ชั่วโมงเรียน_ต่อสัปดาห์      วันที่ลงทะเบียน
count                18.000000                   20
mean                 21.388889  2024-01-14 03:36:00
min                  10.000000  2023-12-17 00:00:00
25%                  16.500000  2024-01-01 18:00:00
50%                  21.500000  2024-01-19 00:00:00
75%                  25.750000  2024-01-24 06:00:00
max                  35.000000  2024-02-09 00:00:00
std                   6.598920                  NaN

describe เป็นการทำข้อมูลให้เป็นค่าสถิติเชิงพรรณนา

In [24]:
missing_counts = df_master.isnull().sum()
print("\n❌ ค่าหายในแต่ละคอลัมน์:")
for col, count in missing_counts[missing_counts > 0].items():
    percentage = (count / len(df_master)) * 100
    print(f"   - {col}: {count} ค่า ({percentage:.1f}%)")

❌ ค่าหายในแต่ละคอลัมน์:
   - ชื่อ: 1 ค่า (5.0%)
   - อายุ: 3 ค่า (15.0%)
   - เพศ: 2 ค่า (10.0%)
   - คณะ: 2 ค่า (10.0%)
   - GPA: 2 ค่า (10.0%)
   - ส่วนสูง_cm: 1 ค่า (5.0%)
   - น้ำหนัก_kg: 2 ค่า (10.0%)
   - ชั่วโมงเรียน_ต่อสัปดาห์: 2 ค่า (10.0%)

ค่าที่หายไปในแต่ละ column ว่ามีกี่ค่า ที่หายไป

In [36]:
(df_master)

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-01
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-07
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-19
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-02
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-24
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-19
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-22
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-09
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-01-31
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-19
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-25
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-17
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2024-01-15
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2023-12-25
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-01-23
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-05
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-19
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2023-12-28
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-10
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-25

ข้อมูลก่อนโดนลบค่าที่หาย

In [38]:
df_clean = df_master.dropna()

ลบค่าที่หายออก

In [39]:
df_clean

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-01
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-07
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-02
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-24
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-19
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-22
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-09
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-01-31
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-19
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2024-01-15
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2023-12-25
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-01-23
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-05
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-19

ข้อมูลหลังโดนลบแล้ว

In [40]:
print(f"\nผลการลบ - ก่อนลบ {len(df_master)} แถว, หลังลบ {len(df_clean)} แถว")

ผลการลบ - ก่อนลบ 20 แถว, หลังลบ 14 แถว

In [41]:
df_master

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-01
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-07
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-19
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-02
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-24
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-19
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-22
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-09
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-01-31
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-19
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-25
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-17
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2024-01-15
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2023-12-25
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-01-23
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-05
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-19
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2023-12-28
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-10
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-25

ค่าก่อนเติมค่า

In [43]:
mean_age = df_master['อายุ'].mean()
df_master['อายุ'].fillna(mean_age, inplace=True)

หาค่าเฉลี่ย จะทำการข้ามข้อมูลว่างอัตโนมัติ

In [44]:
print(f"\nค่าเฉลี่ยอายุ - {mean_age:.1f} ปี")

ค่าเฉลี่ยอายุ - 28.5 ปี

เกี่ยวกับค่าเฉลี่ยเหมาะกับพวกชุดข้อมูลตัวเลข

In [45]:
print(df_master)

    รหัสนักศึกษา      ชื่อ        อายุ     เพศ             คณะ   GPA  \
0          64001     สมชาย   20.000000     ชาย     วิทยาศาสตร์  3.21
1          64002    สมหญิง   21.000000    หญิง           วิทย์  3.45
2          64003       NaN   28.470588    Male         Science  3.67
3          64004  สมศักดิ์   22.000000       ช  คณะวิทยาศาสตร์ -1.00
4          64005      สมใจ   19.000000       ญ           วิศวะ  3.89
5          64006     กานต์  150.000000     ชาย     Engineering  3.12
6          64007     กิตติ   21.000000    หญิง        วิศวกรรม  4.50
7          64008      จิรา   20.000000       F      ศิลปศาสตร์  2.98
8          64009    ชนาธิป   23.000000       M            Arts  3.34
9          64010      ดารา   21.000000    หญิง           ศิลป์  3.56
10         64011      ธีระ   28.470588     NaN             NaN  3.78
11         64012       นภา   22.000000     ชาย           วิทย์   NaN
12         64013     บุญมี   20.000000    หญิง           วิศวฯ  3.23
13         64014     ปรีชา   21.000000     ชาย    Liberal Arts  3.45
14         64015     พิมพ์   22.000000  Female             Sci  3.67
15         64016      ภูมิ   19.000000       ช     วิทยาศาสตร์  3.89
16         64017      มานี   20.000000       ญ  วิศวกรรมศาสตร์  3.01
17         64018      ยุพา   21.000000    หญิง             NaN  3.23
18         64019     รัตนา   28.470588     ชาย      ศิลปศาสตร์   NaN
19         64020     ลัดดา   22.000000     NaN         Science  3.45

    ส่วนสูง_cm  น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0        170.0        65.0                     15.0      2024-01-01
1        165.0        58.0                     20.0      2024-02-07
2        175.0         NaN                     25.0      2024-01-19
3        168.0        70.0                     10.0      2024-01-02
4        160.0        52.0                     30.0      2024-01-24
5        172.0        75.0                     12.0      2023-12-19
6        158.0        48.0                     35.0      2024-01-22
7        180.0        82.0                     18.0      2024-02-09
8        163.0        55.0                     22.0      2024-01-31
9        167.0        60.0                     28.0      2024-01-19
10         NaN        68.0                      NaN      2024-01-25
11       171.0         NaN                     16.0      2023-12-17
12       169.0        72.0                     24.0      2024-01-15
13       164.0        54.0                     19.0      2023-12-25
14       162.0        56.0                     26.0      2024-01-23
15       173.0        78.0                     14.0      2024-01-05
16       166.0        62.0                     21.0      2024-01-19
17       161.0        50.0                     27.0      2023-12-28
18       174.0        76.0                      NaN      2024-01-10
19       168.0        64.0                     23.0      2024-01-25

In [48]:
df_master['คณะ'].fillna(df_master['คณะ'].mode()[0], inplace=True)

เติมค่าที่พบบ่อยมากที่สุดลงในช่องว่าง พบตัวไหนมากสุดตัวนั้นอยู่ช่องว่าง

In [49]:
df_master

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-01
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-07
2,64003,NaN,28.470588,Male,Science,3.67,175.0,NaN,25.0,2024-01-19
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-02
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-24
5,64006,กานต์,150.000000,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-19
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-22
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-09
8,64009,ชนาธิป,23.000000,M,Arts,3.34,163.0,55.0,22.0,2024-01-31
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-19
10,64011,ธีระ,28.470588,NaN,Science,3.78,NaN,68.0,NaN,2024-01-25
11,64012,นภา,22.000000,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-17
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2024-01-15
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2023-12-25
14,64015,พิมพ์,22.000000,Female,Sci,3.67,162.0,56.0,26.0,2024-01-23
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-05
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-19
17,64018,ยุพา,21.000000,หญิง,Science,3.23,161.0,50.0,27.0,2023-12-28
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-10
19,64020,ลัดดา,22.000000,NaN,Science,3.45,168.0,64.0,23.0,2024-01-25

In [63]:
def standardize_faculty(name):
    if name in ['วิทยาศาสตร์', 'วิทย์', 'Science', 'คณะวิทยาศาสตร์', 'Sci']:
        return 'วิทยาศาสตร์'
    elif name in ['ศิลปศาสตร์', 'ศิลป์', 'Arts', 'Liberal Arts']:
        return 'ศิลปศาสตร์'
    elif name in ['วิศวะ', 'วิศวกรรม', 'วิศวฯ', 'Engineering', 'วิศวกรรมศาสตร์']:
        return 'วิศวกรรมศาสตร์'
    else:
        return name

กำหนดเงื่อนไขในการเปลี่ยนใช้คณะให้เป็นคณะมาตรฐาณที่ตั้ง

In [64]:
df_master['คณะ_มาตรฐาน'] = df_master['คณะ'].apply(standardize_faculty)

แสดงคำว่า คณะมาตรฐสนในตาราง

In [65]:
df_master

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-01,วิทยาศาสตร์
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-07,วิทยาศาสตร์
2,64003,NaN,28.470588,Male,Science,3.67,175.0,NaN,25.0,2024-01-19,วิทยาศาสตร์
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-02,วิทยาศาสตร์
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-24,วิศวกรรมศาสตร์
5,64006,กานต์,150.000000,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-19,วิศวกรรมศาสตร์
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-22,วิศวกรรมศาสตร์
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-09,ศิลปศาสตร์
8,64009,ชนาธิป,23.000000,M,Arts,3.34,163.0,55.0,22.0,2024-01-31,ศิลปศาสตร์
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-19,ศิลปศาสตร์
10,64011,ธีระ,28.470588,NaN,Science,3.78,NaN,68.0,NaN,2024-01-25,วิทยาศาสตร์
11,64012,นภา,22.000000,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-17,วิทยาศาสตร์
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2024-01-15,วิศวกรรมศาสตร์
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2023-12-25,ศิลปศาสตร์
14,64015,พิมพ์,22.000000,Female,Sci,3.67,162.0,56.0,26.0,2024-01-23,วิทยาศาสตร์
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-05,วิทยาศาสตร์
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-19,วิศวกรรมศาสตร์
17,64018,ยุพา,21.000000,หญิง,Science,3.23,161.0,50.0,27.0,2023-12-28,วิทยาศาสตร์
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-10,ศิลปศาสตร์
19,64020,ลัดดา,22.000000,NaN,Science,3.45,168.0,64.0,23.0,2024-01-25,วิทยาศาสตร์

ข้อมูลมีคณะมาตรฐานขึ้นแล้ว

In [67]:
print(f"\nค่าเฉลี่ยอายุ (รวมค่าผิดปกติ) - {df_master['อายุ'].mean():.2f}")

ค่าเฉลี่ยอายุ (รวมค่าผิดปกติ) - 28.47

In [69]:
Q1 = df_master['อายุ'].quantile(0.25)
Q3 = df_master['อายุ'].quantile(0.75)
IQR = Q3 - Q1

In [70]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# กรองค่าผิดปกติ
df_no_outliers = df_master[(df_master['อายุ'] >= lower_bound) & (df_master['อายุ'] <= upper_bound)]

print(f"\nขอบเขตล่าง - {lower_bound}")
print(f"ขอบเขตบน - {upper_bound}")
print(f"\nข้อมูลหลังกรองค่าผิดปกติ")
print(df_no_outliers)
print(f"\nค่าเฉลี่ยอายุ (หลังกรองค่าผิดปกติ) - {df_no_outliers['อายุ'].mean():.2f}")

ขอบเขตล่าง - 16.625
ขอบเขตบน - 25.625

ข้อมูลหลังกรองค่าผิดปกติ
    รหัสนักศึกษา      ชื่อ  อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001     สมชาย  20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1          64002    สมหญิง  21.0    หญิง           วิทย์  3.45       165.0
3          64004  สมศักดิ์  22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4          64005      สมใจ  19.0       ญ           วิศวะ  3.89       160.0
6          64007     กิตติ  21.0    หญิง        วิศวกรรม  4.50       158.0
7          64008      จิรา  20.0       F      ศิลปศาสตร์  2.98       180.0
8          64009    ชนาธิป  23.0       M            Arts  3.34       163.0
9          64010      ดารา  21.0    หญิง           ศิลป์  3.56       167.0
11         64012       นภา  22.0     ชาย           วิทย์   NaN       171.0
12         64013     บุญมี  20.0    หญิง           วิศวฯ  3.23       169.0
13         64014     ปรีชา  21.0     ชาย    Liberal Arts  3.45       164.0
14         64015     พิมพ์  22.0  Female             Sci  3.67       162.0
15         64016      ภูมิ  19.0       ช     วิทยาศาสตร์  3.89       173.0
16         64017      มานี  20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0
17         64018      ยุพา  21.0    หญิง         Science  3.23       161.0
19         64020     ลัดดา  22.0     NaN         Science  3.45       168.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน     คณะ_มาตรฐาน
0         65.0                     15.0      2024-01-01     วิทยาศาสตร์
1         58.0                     20.0      2024-02-07     วิทยาศาสตร์
3         70.0                     10.0      2024-01-02     วิทยาศาสตร์
4         52.0                     30.0      2024-01-24  วิศวกรรมศาสตร์
6         48.0                     35.0      2024-01-22  วิศวกรรมศาสตร์
7         82.0                     18.0      2024-02-09      ศิลปศาสตร์
8         55.0                     22.0      2024-01-31      ศิลปศาสตร์
9         60.0                     28.0      2024-01-19      ศิลปศาสตร์
11         NaN                     16.0      2023-12-17     วิทยาศาสตร์
12        72.0                     24.0      2024-01-15  วิศวกรรมศาสตร์
13        54.0                     19.0      2023-12-25      ศิลปศาสตร์
14        56.0                     26.0      2024-01-23     วิทยาศาสตร์
15        78.0                     14.0      2024-01-05     วิทยาศาสตร์
16        62.0                     21.0      2024-01-19  วิศวกรรมศาสตร์
17        50.0                     27.0      2023-12-28     วิทยาศาสตร์
19        64.0                     23.0      2024-01-25     วิทยาศาสตร์

ค่าเฉลี่ยอายุ (หลังกรองค่าผิดปกติ) - 20.88

df_no_outliers = df_master[(df_master['อายุ'] >= lower_bound) & (df_master['อายุ'] <= upper_bound)] คือการเก็บค่า เก็บเฉพาะแถวที่อายุอยู่ในช่วงที่กำหนดแถวที่เกินจะถูกตัดออก

In [72]:
data_encoded = pd.get_dummies(df_master, columns=['คณะ'])
data_encoded = data_encoded.replace({True: 1, False: 0}) #ทำให้ true false เป็น 0 1 ใช้ .replace
print(data_encoded)

    รหัสนักศึกษา      ชื่อ        อายุ     เพศ   GPA  ส่วนสูง_cm  น้ำหนัก_kg  \
0          64001     สมชาย   20.000000     ชาย  3.21       170.0        65.0
1          64002    สมหญิง   21.000000    หญิง  3.45       165.0        58.0
2          64003       NaN   28.470588    Male  3.67       175.0         NaN
3          64004  สมศักดิ์   22.000000       ช -1.00       168.0        70.0
4          64005      สมใจ   19.000000       ญ  3.89       160.0        52.0
5          64006     กานต์  150.000000     ชาย  3.12       172.0        75.0
6          64007     กิตติ   21.000000    หญิง  4.50       158.0        48.0
7          64008      จิรา   20.000000       F  2.98       180.0        82.0
8          64009    ชนาธิป   23.000000       M  3.34       163.0        55.0
9          64010      ดารา   21.000000    หญิง  3.56       167.0        60.0
10         64011      ธีระ   28.470588     NaN  3.78         NaN        68.0
11         64012       นภา   22.000000     ชาย   NaN       171.0         NaN
12         64013     บุญมี   20.000000    หญิง  3.23       169.0        72.0
13         64014     ปรีชา   21.000000     ชาย  3.45       164.0        54.0
14         64015     พิมพ์   22.000000  Female  3.67       162.0        56.0
15         64016      ภูมิ   19.000000       ช  3.89       173.0        78.0
16         64017      มานี   20.000000       ญ  3.01       166.0        62.0
17         64018      ยุพา   21.000000    หญิง  3.23       161.0        50.0
18         64019     รัตนา   28.470588     ชาย   NaN       174.0        76.0
19         64020     ลัดดา   22.000000     NaN  3.45       168.0        64.0

    ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน     คณะ_มาตรฐาน  ...  คณะ_Science  \
0                      15.0      2024-01-01     วิทยาศาสตร์  ...            0
1                      20.0      2024-02-07     วิทยาศาสตร์  ...            0
2                      25.0      2024-01-19     วิทยาศาสตร์  ...            1
3                      10.0      2024-01-02     วิทยาศาสตร์  ...            0
4                      30.0      2024-01-24  วิศวกรรมศาสตร์  ...            0
5                      12.0      2023-12-19  วิศวกรรมศาสตร์  ...            0
6                      35.0      2024-01-22  วิศวกรรมศาสตร์  ...            0
7                      18.0      2024-02-09      ศิลปศาสตร์  ...            0
8                      22.0      2024-01-31      ศิลปศาสตร์  ...            0
9                      28.0      2024-01-19      ศิลปศาสตร์  ...            0
10                      NaN      2024-01-25     วิทยาศาสตร์  ...            1
11                     16.0      2023-12-17     วิทยาศาสตร์  ...            0
12                     24.0      2024-01-15  วิศวกรรมศาสตร์  ...            0
13                     19.0      2023-12-25      ศิลปศาสตร์  ...            0
14                     26.0      2024-01-23     วิทยาศาสตร์  ...            0
15                     14.0      2024-01-05     วิทยาศาสตร์  ...            0
16                     21.0      2024-01-19  วิศวกรรมศาสตร์  ...            0
17                     27.0      2023-12-28     วิทยาศาสตร์  ...            1
18                      NaN      2024-01-10      ศิลปศาสตร์  ...            0
19                     23.0      2024-01-25     วิทยาศาสตร์  ...            1

    คณะ_คณะวิทยาศาสตร์  คณะ_วิทยาศาสตร์  คณะ_วิทย์  คณะ_วิศวกรรม  \
0                    0                1          0             0
1                    0                0          1             0
2                    0                0          0             0
3                    1                0          0             0
4                    0                0          0             0
5                    0                0          0             0
6                    0                0          0             1
7                    0                0          0             0
8                    0                0          0             0
9                    0                0          0             0
10                   0                0          0             0
11                   0                0          1             0
12                   0                0          0             0
13                   0                0          0             0
14                   0                0          0             0
15                   0                1          0             0
16                   0                0          0             0
17                   0                0          0             0
18                   0                0          0             0
19                   0                0          0             0

    คณะ_วิศวกรรมศาสตร์  คณะ_วิศวฯ  คณะ_วิศวะ  คณะ_ศิลปศาสตร์  คณะ_ศิลป์
0                    0          0          0               0          0
1                    0          0          0               0          0
2                    0          0          0               0          0
3                    0          0          0               0          0
4                    0          0          1               0          0
5                    0          0          0               0          0
6                    0          0          0               0          0
7                    0          0          0               1          0
8                    0          0          0               0          0
9                    0          0          0               0          1
10                   0          0          0               0          0
11                   0          0          0               0          0
12                   0          1          0               0          0
13                   0          0          0               0          0
14                   0          0          0               0          0
15                   0          0          0               0          0
16                   1          0          0               0          0
17                   0          0          0               0          0
18                   0          0          0               1          0
19                   0          0          0               0          0

[20 rows x 24 columns]

In [78]:
df_master

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-01,วิทยาศาสตร์
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-07,วิทยาศาสตร์
2,64003,NaN,28.470588,Male,Science,3.67,175.0,NaN,25.0,2024-01-19,วิทยาศาสตร์
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-02,วิทยาศาสตร์
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-24,วิศวกรรมศาสตร์
5,64006,กานต์,150.000000,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-19,วิศวกรรมศาสตร์
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-22,วิศวกรรมศาสตร์
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-09,ศิลปศาสตร์
8,64009,ชนาธิป,23.000000,M,Arts,3.34,163.0,55.0,22.0,2024-01-31,ศิลปศาสตร์
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-19,ศิลปศาสตร์
10,64011,ธีระ,28.470588,NaN,Science,3.78,NaN,68.0,NaN,2024-01-25,วิทยาศาสตร์
11,64012,นภา,22.000000,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-17,วิทยาศาสตร์
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2024-01-15,วิศวกรรมศาสตร์
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2023-12-25,ศิลปศาสตร์
14,64015,พิมพ์,22.000000,Female,Sci,3.67,162.0,56.0,26.0,2024-01-23,วิทยาศาสตร์
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-05,วิทยาศาสตร์
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-19,วิศวกรรมศาสตร์
17,64018,ยุพา,21.000000,หญิง,Science,3.23,161.0,50.0,27.0,2023-12-28,วิทยาศาสตร์
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-10,ศิลปศาสตร์
19,64020,ลัดดา,22.000000,NaN,Science,3.45,168.0,64.0,23.0,2024-01-25,วิทยาศาสตร์

In [82]:
# ตัวอย่าง - ข้อมูลการซื้อกาแฟ
coffee_data = pd.DataFrame({
    'วันเวลา': pd.to_datetime(['2024-01-15 07:30', '2024-01-15 12:00',
                               '2024-01-15 16:30', '2024-01-16 08:00']),
    'ยอดขาย': [1500, 3200, 2100, 1800]
})

# สร้าง features ใหม่
coffee_data['ชั่วโมง'] = coffee_data['วันเวลา'].dt.hour
coffee_data['วันในสัปดาห์'] = coffee_data['วันเวลา'].dt.day_name()
coffee_data['ช่วงเวลา'] = pd.cut(coffee_data['ชั่วโมง'],
                                  bins=[0, 10, 14, 18, 24],
                                  labels=['เช้า', 'กลางวัน', 'บ่าย', 'เย็น'])

print(coffee_data[['วันเวลา', 'ช่วงเวลา', 'ยอดขาย']])

              วันเวลา ช่วงเวลา  ยอดขาย
0 2024-01-15 07:30:00     เช้า    1500
1 2024-01-15 12:00:00  กลางวัน    3200
2 2024-01-15 16:30:00     บ่าย    2100
3 2024-01-16 08:00:00     เช้า    1800

ใช้โค้ดตัวอย่างเพราะทำไม่เป็น TT โค้ดนี้เป็นการแบ่งช่วงเวลาของวันนั้น

In [84]:
df_master['BMI'] = df_master['น้ำหนัก_kg'] / (df_master['ส่วนสูง_cm']/100)**2
df_master['สุขภาพ'] = pd.cut(df_master['BMI'],
                                   bins=[0, 18.5, 25, 30, 100],
                                   labels=['ผอม', 'ปกติ', 'อ้วน', 'อ้วนมาก'])

df_master[['ชื่อ', 'BMI', 'สุขภาพ']]

        ชื่อ        BMI สุขภาพ
0      สมชาย  22.491349   ปกติ
1     สมหญิง  21.303949   ปกติ
2        NaN        NaN    NaN
3   สมศักดิ์  24.801587   ปกติ
4       สมใจ  20.312500   ปกติ
5      กานต์  25.351541   อ้วน
6      กิตติ  19.227688   ปกติ
7       จิรา  25.308642   อ้วน
8     ชนาธิป  20.700817   ปกติ
9       ดารา  21.513859   ปกติ
10      ธีระ        NaN    NaN
11       นภา        NaN    NaN
12     บุญมี  25.209201   อ้วน
13     ปรีชา  20.077335   ปกติ
14     พิมพ์  21.338211   ปกติ
15      ภูมิ  26.061679   อ้วน
16      มานี  22.499637   ปกติ
17      ยุพา  19.289379   ปกติ
18     รัตนา  25.102391   อ้วน
19     ลัดดา  22.675737   ปกติ

df_master['BMI'] = df_master['น้ำหนัก_kg'] / (df_master['ส่วนสูง_cm']/100)**2
การหาค่า BMI ใช้สูตรในการคำนวน
pd.cut(df_master['BMI'], bins=[0, 18.5, 25, 30, 100], labels=['ผอม', 'ปกติ', 'อ้วน', 'อ้วนมาก']) การจัดกลุ่มของข้อมูล

In [95]:
df_master

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน,BMI,สุขภาพ
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-01,วิทยาศาสตร์,22.491349,ปกติ
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-07,วิทยาศาสตร์,21.303949,ปกติ
2,64003,NaN,28.470588,Male,Science,3.67,175.0,NaN,25.0,2024-01-19,วิทยาศาสตร์,NaN,NaN
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-02,วิทยาศาสตร์,24.801587,ปกติ
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-24,วิศวกรรมศาสตร์,20.312500,ปกติ
5,64006,กานต์,150.000000,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-19,วิศวกรรมศาสตร์,25.351541,อ้วน
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-22,วิศวกรรมศาสตร์,19.227688,ปกติ
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-09,ศิลปศาสตร์,25.308642,อ้วน
8,64009,ชนาธิป,23.000000,M,Arts,3.34,163.0,55.0,22.0,2024-01-31,ศิลปศาสตร์,20.700817,ปกติ
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-19,ศิลปศาสตร์,21.513859,ปกติ
10,64011,ธีระ,28.470588,NaN,Science,3.78,NaN,68.0,NaN,2024-01-25,วิทยาศาสตร์,NaN,NaN
11,64012,นภา,22.000000,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-17,วิทยาศาสตร์,NaN,NaN
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2024-01-15,วิศวกรรมศาสตร์,25.209201,อ้วน
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2023-12-25,ศิลปศาสตร์,20.077335,ปกติ
14,64015,พิมพ์,22.000000,Female,Sci,3.67,162.0,56.0,26.0,2024-01-23,วิทยาศาสตร์,21.338211,ปกติ
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-05,วิทยาศาสตร์,26.061679,อ้วน
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-19,วิศวกรรมศาสตร์,22.499637,ปกติ
17,64018,ยุพา,21.000000,หญิง,Science,3.23,161.0,50.0,27.0,2023-12-28,วิทยาศาสตร์,19.289379,ปกติ
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-10,ศิลปศาสตร์,25.102391,อ้วน
19,64020,ลัดดา,22.000000,NaN,Science,3.45,168.0,64.0,23.0,2024-01-25,วิทยาศาสตร์,22.675737,ปกติ

ยังทำเปลี่ยนพวกค่า ว่าง ยังไม่สมบูรณ์ เพราะข้อมูลบางคนไม่สามารถสมมุติขึ้นมาได้หากเจ้าตัวไม่ใส่ข้อมูลส่วนตัวมาครบ

In [102]:
assert df_master.isnull().sum().sum() == 0, "ยังมีค่าหายอยู่!"

AssertionError: ยังมีค่าหายอยู่!

 assert ใช้เพื่อตรวจสอบคุณภาพข้อมูลหลังทำความสะอาด